# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright (c) 2023-2026 Maulik Mistry

env_vars+=(
    # Requires the nvidia-vaapi-driver install.
    LIBVA_DRIVER_NAME=nvidia
)

app_args+=(
    # Requires the nvidia-vaapi-driver install.
    --enable-features=AcceleratedVideoDecodeLinuxGL,VaapiOnNvidiaGPUs
    --ignore-gpu-blocklist
    --use-gl=angle
    --use-angle=gl
    --ozone-platform=wayland
)
